const depName = {
  quetzaltenango: "Quetzaltenango",
  huehuetenango: "Huehuetenango",
  chimaltenango: "Chimaltenango",
  suchitepequez: "Suchitepéquez",
  sacatepequez: "Sacatepéquez",
  altaverapaz: "Alta Verapaz",
  bajaverapaz: "Baja Verapaz",
  totonicapan: "Totonicapán",
  retalhuleu: "Retalhuleu",
  chiquimula: "Chiquimula",
  guatemala: "Guatemala",
  santarosa: "Santa Rosa",
  escuintla: "Escuintla",
  san_marcos: "San Marcos",
  el_progreso: "El Progreso",
  jutiapa: "Jutiapa",
  zacapa: "Zacapa",
  jalapa: "Jalapa",
  quiche: "Quiché",
  solola: "Sololá",
  izabal: "Izabal",
  peten: "Petén",

  // HONDURAS
  atlantida: "Atlántida",
  choluteca: "Choluteca",
  colon: "Colón",
  comayagua: "Comayagua",
  copan: "Copán",
  cortes: "Cortés",
  el_paraiso: "El Paraíso",
  francisco_morazan: "Francisco Morazán",
  gracias_a_dios: "Gracias a Dios",
  intibuca: "Intibucá",
  islas_bahia: "Islas de la Bahía",
  la_paz: "La Paz",
  lempira: "Lempira",
  ocotepeque: "Ocotepeque",
  olancho: "Olancho",
  santa_barbara: "Santa Bárbara",
  valle: "Valle",
  yoro: "Yoro",

  // SALVAD
  ahuachapan: "Ahuachapán",
  cabanas: "Cabañas",
  chalatenango: "Chalatenango",
  cuscatlan: "Cuscatlán",
  la_libertad: "La Libertad",
  la_paz: "La Paz",
  la_union: "La Unión",
  morazan: "Morazán",
  san_miguel: "San Miguel",
  san_salvador: "San Salvador",
  san_vicente: "San Vicente",
  santa_ana: "Santa Ana",
  sonsonate: "Sonsonate",
  usulutan: "Usulután",
  
};

export default depName;
